//! Fast estimation of the accurate representation of a float.
//!
//! This is currently a working prototype, and aims to replace
//! `moderate_path` in `correct`.
//!
//! Based off the Golang implementation of the Eisel-Lemire algorithm,
//! found here:
//!     https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/strconv/eisel_lemire.go
//!
//! The original algorithm may be found here:
//!     https://github.com/lemire/fast_double_parser
//!
//! And an in-depth blogpost describing the algorithms may be found here:
//!     https://nigeltao.github.io/blog/2020/eisel-lemire.html

// TODO(ahuszagh) Going to need to use small/large powers
//      I'm not hard-coding an array for 360+ powers-of-2
//      I already have cached large_powers

// The powers-of-10 look-up table is generated by this Go program.
// The two u64 columns are explicitly printed, and the one i32 column
// is implied by a linear expression with slope log(10)/log(2).
