[package]
name = "algorithm"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
edition = "2021"
publish = false

[dependencies.lexical-util]
path = "../../../lexical-util"
default-features = false
features = []

[dependencies.lexical-parse-float]
path = "../../../lexical-parse-float"
default-features = false
features = []

[dev-dependencies]
criterion = { version = "0.5.0", features = ["html_reports"] }
fastrand = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["std", "integers", "floats", "json"]
std = ["lexical-util/std", "lexical-parse-float/std"]
integers = ["lexical-util/integers"]
floats = ["lexical-util/floats"]
json = []

[[bench]]
name = "bigint"
path = "bigint.rs"
harness = false

[[bench]]
name = "division"
path = "division.rs"
harness = false
