[package]
name = "lexical-parse-float-correctness"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
edition = "2021"
publish = false

[dependencies.lexical-parse-float]
path = "../.."
default-features = false
features = []

[dependencies.lexical-util]
path = "../../../lexical-util"
default-features = false
features = []

[dependencies]
rand = "0.8.5"
indicatif = { version = "0.17.8", default-features = false }
num = "0.4.3"
rand_chacha = "0.3"
rayon = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
rand_isaac = ">=0.3.0"
regex = { version = ">=1.10.6", optional = true}
lazy_static = { version = ">=1.5.0", optional = true }

[features]
std = ["lexical-parse-float/std", "lexical-util/std"]
power-of-two = ["lexical-parse-float/power-of-two", "lexical-util/power-of-two"]
radix = ["lexical-parse-float/radix", "lexical-util/radix"]
format = ["lexical-parse-float/format", "lexical-util/format"]
compact = ["lexical-parse-float/compact"]
digit-separator = ["format", "regex", "lazy_static"]

[workspace]

[lib]
name = "test_parse_random"
path = "test-parse-random/lib.rs"

[[bin]]
name = "test-parse-random"
path = "test-parse-random/main.rs"

[[bin]]
name = "test-parse-golang"
path = "test-parse-golang/main.rs"

[[bin]]
name = "test-parse-unittests"
path = "test-parse-unittests/main.rs"
