[package]
name = "lexical-write-integer-benchmark"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
edition = "2018"
publish = false

[dependencies.lexical-util]
path = "../../lexical-util"
default-features = false
features = []

[dependencies.lexical-write-integer]
path = "../../lexical-write-integer"
default-features = false
features = []

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
itoa = { version = "0.4", features = ["i128"] }
fastrand = "1.4"
lazy_static = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["std", "integers", "json"]
std = ["lexical-util/std", "lexical-write-integer/std"]
radix = ["lexical-util/radix", "lexical-write-integer/radix"]
power-of-two = ["lexical-util/power-of-two", "lexical-write-integer/power-of-two"]
format = ["lexical-util/format", "lexical-write-integer/format"]
compact = ["lexical-util/compact", "lexical-write-integer/compact"]
integers = []
json = []

[[bench]]
name = "json"
path = "json.rs"
harness = false

[[bench]]
name = "random"
path = "random.rs"
harness = false
