name: Cross

on:
  [pull_request, workflow_dispatch]

# NOTE: Use older toolchains since there's bugs cross-compiling
# for some more recent architectures.
jobs:
  cross:
    name: Rust ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          # Android
          - aarch64-linux-android
          - arm-linux-androideabi
          - armv7-linux-androideabi
          - i686-linux-android
          - x86_64-linux-android

          # Linux
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          # NOTE: Required for issue #218
          - i586-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          # NOTE: This fails on cross v0.2.1, which is unusual since
          # manually invoking the failing tests with qemu-5.1.0 passes.
          #- powerpc64le-unknown-linux-gnu
          # NOTE: This has glibc linker issues. Restore later.
          #- x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

          # Windows
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{matrix.target}}
      - name: Install Cross
        run: |
          cargo install cross@0.2.5
          rustup toolchain add 1.65.0
      - name: Run Check
        run: |
          cross +1.65.0 check --target ${{matrix.target}}
      - name: Run Simple Test
        run: |
          cross +1.65.0 test --target ${{matrix.target}}
      - name: Run Feature Test
        run: |
          cross +1.65.0 test --target ${{matrix.target}}  --features=radix,format,compact

  notest:
    name: Rust ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          # Linux
          - powerpc64-unknown-linux-gnu
          - s390x-unknown-linux-gnu

          # FreeBSD
          - i686-unknown-freebsd
          - x86_64-unknown-freebsd
          - x86_64-unknown-netbsd

          # MIPS
          # These targets have been removed from Tier 2
          # support, so we're using an older compiler and
          # just checking they can be checked.
          - mips-unknown-linux-gnu
          - mips64-unknown-linux-gnuabi64
          - mips64el-unknown-linux-gnuabi64
          - mipsel-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install Cross
        run: |
          cargo install cross@0.2.5
          rustup toolchain add 1.65.0
          rustup toolchain install 1.65.0 --target ${{matrix.target}} --profile minimal --no-self-update
      - name: Run check
        run: |
          cross +1.65.0 check --target ${{matrix.target}}
