name: Miri

on: [workflow_dispatch]
jobs:
  Miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo check
      - run: cargo build
      - run: rustup component add --toolchain nightly miri
      # Test with all features: this won't test the non-compact code paths however
      - run: cargo miri test --all-features
      - run: cargo miri test --features radix,format,write-integers,write-floats,parse-integers,parse-floats
