name: Miri

on: [workflow_dispatch]
jobs:
  Miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo check
      - run: cargo build
      - run: ci/miri.sh
