name: OSX

on:
  [pull_request, workflow_dispatch]

jobs:
  cross:
    name: Rust MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo check
      - run: cargo test
      - run: cargo test --features=radix,format,compact
