name: Valgrind

on:
  [push, pull_request, workflow_dispatch]

jobs:
  valgrind:
    name: Valgrind Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
      - run: sudo apt-get update
      - run: sudo apt-get install valgrind
      - run: cargo +nightly install cargo-valgrind
      - run: cargo +nightly valgrind test --release
      - run: cargo +nightly valgrind test --all-features --release
